### ISSUE TITLE
Issues with physics demos

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/MiniPhysics-By-38A#1]
1. Walking up 45 degree slopes sometimes resets horizontal velocity.
2. Character can eventually nudged off from circular moving platform.
3. I think, that FPS counter is needed as QT demo is a bit laggy on my PC.
   ![specs](https://cloud.githubusercontent.com/assets/7596025/17074173/228a860e-5081-11e6-984c-9950859d71c8.png)
4. Also, speed-adding stack demo should have an option to add non-moving blocks (H-speed = 0)
5. Also playable block don`t get pushed sideways when a solid moving block pushes him into slope block.
   ![slope_push](https://cloud.githubusercontent.com/assets/7596025/17074261/5e5f0c3a-5082-11e6-9494-bae044315590.png)

**Comment by Wohlstand** [comment]
About 3 - It's no lag, it's large timer interval to have watching physics more detailed
About 4 - that must be applied to dynamic objects, most of blocks here are static: wall, floor, celling, etc. and there are can't be affected by dynamic objects. Except destroying :laughing:  EDIT: that speed-adding demo made once just an implementation of algorithm to let me implement it into main demo
About 1, 5 - just an imperfections which I working now
About 2 - that because I must also apply modified Y speed which doesn't doing here. I bet in SMBX 1.3 and SMBX-38A will be same with round-rotating blocks (attached to firebars) EDIT: in SMBX 1.3 fine, but moving layer which attached to moving firebar is bit lags, but in SMBX-38A result is very buggy :yum:

**Comment by Wohlstand** [comment]
Everything here has been fixed

**Comment by Alucard648** [comment]
You missed #5

**Comment by Wohlstand** [comment]
#5 is almost fixed, except you are staying on corner, but fine if you staying on slope without touching corner. This is another thing which also refering to another bug when character fell between slope corners, and speed going to be zeroed.
